## 🛠 Bài tập thực hành 
> **Lưu ý:** Các bạn cần làm phần bài tập này để chuẩn bị cho phiên review lab.

1. Tạo một vector, scalar, matrix và tensor với các giá trị tùy chọn, sử dụng `tf.constant()`.
2. Tìm shape, rank và size của tensor mà bạn vừa tạo ở 1.
3. Tạo hai tensor chứa các giá trị ngẫu nhiên trong khoảng từ 0 đến 1 có shape `[5, 300]`.
4. Nhân hai tensor mà bạn tạo ở 3, sử dụng phép nhân ma trận.
5. Nhân hai tensor mà bạn tạo ở 3, sử dụng tích vô hướng.
6. Tạo một tensor với giá trị ngẫu nhiên trong khoảng từ 0 đến 1 có shape `[224, 224, 3]`.
7. Tìm min và max của tensor bạn đã tạo ở 6.
8. Tạo một tensor với các giá trị tuyệt đối có shape `[1, 224, 224, 3]` rồi nén nó để thay đổi shape thành `[224, 224, 3]`.
9. Tạo một tensor có shape `[10]` sử dụng các giá trị tùy chọn rồi tìm ra chỉ mục nào có giá trị lớn nhất.
10. Mã hóa one-hot tensor bạn vừa tạo ở 9.

In [15]:
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

# Import TensorFlow
import tensorflow as tf
import numpy as np
print(tf.__version__) # tìm số phiên bản (nên là 2.x+)

2.10.0


1. Tạo một vector, scalar, matrix và tensor với các giá trị tùy chọn, sử dụng `tf.constant()`.

In [5]:
scalar = tf.constant(1)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [6]:
vector = tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [7]:
matrix = tf.constant([[1,2],[3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [9]:
tensor = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

2. Tìm shape, rank và size của tensor mà bạn vừa tạo ở 1.

In [12]:
print('tensor shape: ', tensor.shape)
print('tensor rank: ', tensor.ndim)
print('tensor type: ', tensor.dtype)
print('tensor size: ', tf.size(tensor).numpy())

tensor shape:  (2, 2, 2)
tensor rank:  3
tensor type:  <dtype: 'int32'>
tensor size:  8


3. Tạo hai tensor chứa các giá trị ngẫu nhiên trong khoảng từ 0 đến 1 có shape `[5, 300]`.

In [17]:
random1 = tf.constant(np.random.random((5,300)))
random2 = tf.constant(np.random.random((5,300)))
random1, random2

(<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
 array([[0.34237583, 0.22762803, 0.84454308, ..., 0.69040081, 0.26343534,
         0.67969121],
        [0.65214511, 0.22637858, 0.78069602, ..., 0.46175364, 0.14513786,
         0.85883575],
        [0.73884934, 0.88473346, 0.77342049, ..., 0.81083004, 0.29239321,
         0.35270257],
        [0.89170317, 0.24723833, 0.72178372, ..., 0.35890997, 0.45871117,
         0.07545373],
        [0.1865081 , 0.03305636, 0.2110954 , ..., 0.30924957, 0.27908222,
         0.02459416]])>,
 <tf.Tensor: shape=(5, 300), dtype=float64, numpy=
 array([[0.98475896, 0.28827036, 0.21003334, ..., 0.43686811, 0.77117868,
         0.95924216],
        [0.59899846, 0.41766288, 0.05613102, ..., 0.49692327, 0.02617343,
         0.8603274 ],
        [0.64527248, 0.77303529, 0.43133607, ..., 0.29193822, 0.10262372,
         0.76601909],
        [0.01755694, 0.10225621, 0.47520007, ..., 0.98738937, 0.65931311,
         0.89780377],
        [0.59818168, 0.14501394

4. Nhân hai tensor mà bạn tạo ở 3, sử dụng phép nhân ma trận.

In [18]:
random1@tf.transpose(random2)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[82.02172645, 74.22673379, 72.76685346, 76.56439588, 76.70994497],
       [79.88250586, 70.65302013, 72.90975519, 73.55443484, 74.18679269],
       [80.82115148, 75.10063693, 73.6899241 , 78.03075179, 73.62588445],
       [70.55024542, 63.30535336, 67.93442905, 70.63431441, 70.08575335],
       [78.31661493, 73.33302568, 74.81501202, 78.60971711, 78.03334019]])>

In [19]:
tf.matmul(random1, tf.transpose(random2))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[82.02172645, 74.22673379, 72.76685346, 76.56439588, 76.70994497],
       [79.88250586, 70.65302013, 72.90975519, 73.55443484, 74.18679269],
       [80.82115148, 75.10063693, 73.6899241 , 78.03075179, 73.62588445],
       [70.55024542, 63.30535336, 67.93442905, 70.63431441, 70.08575335],
       [78.31661493, 73.33302568, 74.81501202, 78.60971711, 78.03334019]])>

In [21]:
tf.matmul(random1, tf.reshape(random2, (300,5)))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[80.8635025 , 73.52165185, 77.5062303 , 74.20473438, 73.04654797],
       [78.78889864, 74.35577718, 75.3440015 , 71.25746712, 75.67865135],
       [79.20707848, 76.17367123, 77.05455728, 76.17511844, 73.3063277 ],
       [74.05027741, 67.2186703 , 68.94158121, 68.62097775, 65.26688152],
       [81.66862016, 71.75921711, 76.67268815, 75.04057341, 75.92280277]])>

5. Nhân hai tensor mà bạn tạo ở 3, sử dụng tích vô hướng.

In [23]:
tf.tensordot(random1, tf.transpose(random2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[82.02172645, 74.22673379, 72.76685346, 76.56439588, 76.70994497],
       [79.88250586, 70.65302013, 72.90975519, 73.55443484, 74.18679269],
       [80.82115148, 75.10063693, 73.6899241 , 78.03075179, 73.62588445],
       [70.55024542, 63.30535336, 67.93442905, 70.63431441, 70.08575335],
       [78.31661493, 73.33302568, 74.81501202, 78.60971711, 78.03334019]])>

6. Tạo một tensor với giá trị ngẫu nhiên trong khoảng từ 0 đến 1 có shape `[224, 224, 3]`.

In [24]:
random3 = tf.constant(np.random.random((224,224,3)))
random3

<tf.Tensor: shape=(224, 224, 3), dtype=float64, numpy=
array([[[0.16591269, 0.22062545, 0.13270991],
        [0.35038312, 0.25160932, 0.75313081],
        [0.67318826, 0.8141603 , 0.80376691],
        ...,
        [0.28872402, 0.28559611, 0.90519908],
        [0.98757508, 0.81623778, 0.09972744],
        [0.09989545, 0.92834289, 0.37647818]],

       [[0.55325276, 0.36929516, 0.79993097],
        [0.88519218, 0.31625412, 0.75723139],
        [0.23961615, 0.01926325, 0.94268643],
        ...,
        [0.1893758 , 0.92671013, 0.44899214],
        [0.85548271, 0.31221469, 0.13050106],
        [0.65709903, 0.43132221, 0.22683817]],

       [[0.86088648, 0.71369745, 0.78185513],
        [0.05088491, 0.34436386, 0.42442177],
        [0.47202826, 0.87857838, 0.70072725],
        ...,
        [0.27180033, 0.31772668, 0.94345534],
        [0.06860687, 0.93352827, 0.95956925],
        [0.38432203, 0.66610274, 0.26876755]],

       ...,

       [[0.14950513, 0.96251974, 0.28476071],
        [0.77

7. Tìm min và max của tensor bạn đã tạo ở 6.

In [26]:
tf.reduce_min(random3), tf.reduce_max(random3)

(<tf.Tensor: shape=(), dtype=float64, numpy=1.3804983953424887e-05>,
 <tf.Tensor: shape=(), dtype=float64, numpy=0.9999973421282846>)

8. Tạo một tensor với các giá trị tuyệt đối có shape `[1, 224, 224, 3]` rồi nén nó để thay đổi shape thành `[224, 224, 3]`.

In [28]:
random4 = tf.random.Generator.from_seed(42)
random4 = random4.normal(shape=(1, 224, 224, 3))
random4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[-0.7565803 , -0.06854702,  0.07595026],
         [-1.2573844 , -0.23193763, -1.8107855 ],
         [ 0.09988727, -0.50998646, -0.7535805 ],
         ...,
         [ 0.07099114, -0.5095768 ,  0.3482001 ],
         [ 0.15985982, -1.9042184 ,  0.9690504 ],
         [ 0.16251186, -0.07330752, -0.360591  ]],

        [[ 0.18739441, -0.73353654,  1.2104433 ],
         [ 1.5603006 , -0.48115277,  0.6335167 ],
         [-0.5612103 ,  0.06994031,  1.6807095 ],
         ...,
         [-1.9460293 , -0.7977275 ,  0.03092833],
         [ 0.8297488 ,  0.12179119,  1.0506107 ],
         [-1.3097638 ,  0.92536974, -1.1787732 ]],

        [[-0.21711822, -0.73974085, -1.3077081 ],
         [-0.7502274 , -0.37715855, -0.30130875],
         [ 1.0943383 ,  0.255803  ,  0.8011465 ],
         ...,
         [-0.32833767, -0.7794747 ,  0.20049338],
         [-0.09002841,  0.07243238, -0.81940895],
         [ 0.3171264 , -1.6143695 , -1.6824651

In [29]:
random4 = tf.abs(random4)
random4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.7565803 , 0.06854702, 0.07595026],
         [1.2573844 , 0.23193763, 1.8107855 ],
         [0.09988727, 0.50998646, 0.7535805 ],
         ...,
         [0.07099114, 0.5095768 , 0.3482001 ],
         [0.15985982, 1.9042184 , 0.9690504 ],
         [0.16251186, 0.07330752, 0.360591  ]],

        [[0.18739441, 0.73353654, 1.2104433 ],
         [1.5603006 , 0.48115277, 0.6335167 ],
         [0.5612103 , 0.06994031, 1.6807095 ],
         ...,
         [1.9460293 , 0.7977275 , 0.03092833],
         [0.8297488 , 0.12179119, 1.0506107 ],
         [1.3097638 , 0.92536974, 1.1787732 ]],

        [[0.21711822, 0.73974085, 1.3077081 ],
         [0.7502274 , 0.37715855, 0.30130875],
         [1.0943383 , 0.255803  , 0.8011465 ],
         ...,
         [0.32833767, 0.7794747 , 0.20049338],
         [0.09002841, 0.07243238, 0.81940895],
         [0.3171264 , 1.6143695 , 1.6824651 ]],

        ...,

        [[0.4106899 , 0.3995463 , 

In [30]:
random4 = tf.squeeze(random4)
random4.shape

TensorShape([224, 224, 3])

9. Tạo một tensor có shape `[10]` sử dụng các giá trị tùy chọn rồi tìm ra chỉ mục nào có giá trị lớn nhất.

In [32]:
tensor9 = tf.constant(np.random.randint(10, size=(10)))
tensor9

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([2, 8, 3, 5, 0, 3, 3, 0, 7, 4])>

In [33]:
print('index of max value: ', tf.argmax(tensor9).numpy())

index of max value:  1


10. Mã hóa one-hot tensor bạn vừa tạo ở 9.

In [34]:
tf.one_hot(tensor9, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)>